on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - uses: extractions/setup-just@v3
      - run: just build-web
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - uses: extractions/setup-just@v3
      - run: just test